project:
  type: book
  output-dir: docs

book:
  title: "Research Methodologies & Data Analysis Using R"
  author: "Team"
  date: "14/11/2024"
  page-navigation: true
  chapters:
  - index.qmd
  - preface.qmd
  - research_methods.qmd
  - study_design.qmd
  - validity_reliability_research.qmd
  - digital_data.qmd
  - intro_r.qmd
  - statistical_methods.qmd
  - epi_measures.qmd
  - quarto.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

