project:
  type: book
  output-dir: docs

book:
  title: "Research Methodologies & Data Analysis Using R"
  author: "Team"
  date: "14/11/2024"
  page-navigation: true
  chapters:
  - index.qmd
  - preface.qmd
  - part: research_methods.qmd
    chapters:
      - understanding_research.qmd
      - philosophical_underpinning.qmd
      - need_for_research.qmd
      - types_of_research.qmd
      - steps_in_research.qmd
      
  - part: study_design.qmd
    chapters:
      - observational_study_design.qmd
      - descriptive_observational_design.qmd
      - analytical_observational_design.qmd
      - experimental_study_design.qmd
  - part: statistical_methods.qmd
    chapters:
      - descriptive_statistics.qmd
      - graph_descriptive_statistics.qmd
      - num_descriptive_statistics.qmd
      - inferential_statistics.qmd
      - hypothesis_testing.qmd
      - regression_analysis.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

