---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Validity in Research

::: {style="text-align:justify"}

Validity is concerned with the integrity of the conclusions that are generated from a piece of research. 

:::

## Main types of validity typically distinguished in research:

::: {style="text-align:justify"}

 - Measurement Validity
 - Internal Validity
 - External Validity
 - Ecological Validity

:::

## Measurement Validity

::: {style="text-align:justify"}

The soundness or appropriateness of a test or instrument or it could be even an indicator to measure a concept, in measuring what it is designed to measure.

:::

### Several Ways of Establishing Measurement Validity

::: {style="text-align:justify"}

 - **Face Validity**:  Reflects the content of the concept in question.It can be established by consulting experts to see if the measure accurately addresses the intended concept.
 
 - **Content Validity**: Infers that the test measures all aspects contributing to the
concept/variable of interest. 
 
 - **Concurrent Validity**: Infers that the test produces similar results to a previously
validated test.It entails relating a measure to a criterion on which cases (e.g. people) are known to differ and that is relevant to the concept in question.

 - **Predictive Validity**: Infers that the test provides a valid reflection of future
performance using a similar test. Here, the researcher uses a future criterion measure, rather than a contemporary one, as in concurrent validity.

 - **Construct Validity**: Infers not only that the test is measuring what it is supposed to, but also that it is capable of detecting what should exist,theoretically. Therefore relates to hypothetical or intangible constructs, researcher is encouraged to deduce hypotheses from a
theory that is relevant to the concept.

:::

## Conventional Paradigms of Validity

::: {style="text-align:justify"}

 - **Internal validity**: The best approximation of truth or falsity of a statement implying a relationship or its absence between two variables –indicative of causation.

 - **External validity**: The validity with which we infer that the presumed causal relationships can be generalised to and across alternative measures of the cause and effect and across different types of persons, settings and times.

:::

## Ecological Validity

::: {style="text-align:justify"}

Ecological Validity is concerned with the question of whether social scientific findings are applicable to people’s everyday, natural social settings, commonly applicable in social science research.Do the tools/instruments capture the daily life conditions, opinions, values, attitudes, and knowledge base of those studied as expressed in their natural habitat?’

For a more in-depth understanding, refer to additional resources.

- [Validity and Reliability in Quantitative Studies](Heale R and Twycross A (2015) Validity and reliability in quantitative studies. Evidence-Based Nursing 18(3). Royal College of Nursing: 66–67.
)

:::
