---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Validity in Research

Validity is concerned with the integrity of the conclusions that are generated from a piece of research. 

## Main types of validity typically distinguished in research:

 - Measurement Validity
 - Internal Validity
 - External Validity
 - Ecological Validity

## Measurement Validity

The soundness or appropriateness of a test or instrument or it could be even an indicator to measure a concept, in measuring what it is designed to measure.

### Several Ways of Establishing Measurement Validity

 - **Face Validity**, reflects the content of the concept in question.It can be established by consulting experts to see if the measure accurately addresses the intended concept.
 
 - 

## Conventional Paradigms of Validity

 - **Internal validity** 
The best approximation of truth or falsity of a statement implying a relationship or its absence between two variables –indicative of causation.

 - **External validity** 
The validity with which we infer that the presumed causal relationships can be generalised to and across alternative measures of the cause and effect and across different types of persons, settings and times.



