<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.475">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Research Methodologies &amp; Data Analysis Using R - 9&nbsp; Inferential Statistics: Regression Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./hypothesis_testing.html" rel="next">
<link href="./inferential_statistics.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Inferential Statistics: Regression Analysis</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Research Methodologies &amp; Data Analysis Using R</a> 
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">About Book</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface.html" class="sidebar-item-text sidebar-link">Preface</a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./research_methods.html" class="sidebar-item-text sidebar-link">Introduction to Research</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./understanding_research.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Research : Definition &amp; Origin</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./need_for_research.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Why Research?</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./study_design.html" class="sidebar-item-text sidebar-link">Epidemiological Study Designs</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./observational_study_design.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Observational Study Design</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./experimental_study_design.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Experimental Study Design</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./statistical_methods.html" class="sidebar-item-text sidebar-link">Statistical Methods</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./descriptive_statistics.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Descriptive Statistics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./graph_descriptive_statistics.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Descriptive Statistics: Graphical Methods</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./num_descriptive_statistics.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Descriptive Statistics: Numerical Methods</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inferential_statistics.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Inferential Statistics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./regression.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Inferential Statistics: Regression Analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./hypothesis_testing.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">hypothesis_testing.html</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#simple-linear-regression-slr" id="toc-simple-linear-regression-slr" class="nav-link active" data-scroll-target="#simple-linear-regression-slr"><span class="toc-section-number">9.1</span>  Simple Linear Regression (SLR)</a>
  <ul class="collapse">
  <li><a href="#assumptions-of-simple-linear-regression" id="toc-assumptions-of-simple-linear-regression" class="nav-link" data-scroll-target="#assumptions-of-simple-linear-regression"><span class="toc-section-number">9.1.1</span>  Assumptions of Simple Linear Regression</a></li>
  <li><a href="#the-slr-model" id="toc-the-slr-model" class="nav-link" data-scroll-target="#the-slr-model"><span class="toc-section-number">9.1.2</span>  The SLR Model</a></li>
  <li><a href="#interpreting-the-model" id="toc-interpreting-the-model" class="nav-link" data-scroll-target="#interpreting-the-model"><span class="toc-section-number">9.1.3</span>  Interpreting the Model</a></li>
  </ul></li>
  <li><a href="#simple-linear-regression-slr-using-r" id="toc-simple-linear-regression-slr-using-r" class="nav-link" data-scroll-target="#simple-linear-regression-slr-using-r"><span class="toc-section-number">9.2</span>  Simple Linear Regression (SLR) Using R</a>
  <ul class="collapse">
  <li><a href="#simple-linear-regression-with-a-numeric-independent-variable" id="toc-simple-linear-regression-with-a-numeric-independent-variable" class="nav-link" data-scroll-target="#simple-linear-regression-with-a-numeric-independent-variable"><span class="toc-section-number">9.2.1</span>  Simple Linear Regression with a Numeric Independent Variable</a></li>
  <li><a href="#simple-linear-regression-with-a-categorical-independent-variable" id="toc-simple-linear-regression-with-a-categorical-independent-variable" class="nav-link" data-scroll-target="#simple-linear-regression-with-a-categorical-independent-variable"><span class="toc-section-number">9.2.2</span>  Simple Linear Regression with a Categorical Independent Variable</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Inferential Statistics: Regression Analysis</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<div style="text-align:justify">
<p>Regression analysis is a powerful statistical method used to examine the relationship between two or more variables. The goal of regression is to understand how the dependent variable (also called the outcome or response variable) changes when one or more independent variables (also known as predictors or explanatory variables) are varied This method is widely used in various fields such as economics, healthcare, social sciences, and engineering to make predictions, identify trends, and uncover relationships between variables.</p>
<p>There are various types of regression, each suited to different types of data and research questions. Some common types include:</p>
<ul>
<li><p><strong>Linear Regression:</strong> This examines the relationship between one independent variable and one or more dependent variables, assuming a linear relationship between them.</p></li>
<li><p><strong>Logistic Regression:</strong> Used when the dependent variable is categorical, typically binary (e.g., success/failure). It models the probability of the outcome occurring.</p></li>
<li><p><strong>Generalized Linear Models (GLM):</strong> These extend linear regression to handle various types of dependent variables, including count data and proportions, using different link functions. Both linear regression and logistic regression are actually special cases of GLMs. Linear regression uses an identity link function for continuous outcomes, while logistic regression uses a logit link function for binary outcomes. This flexibility makes GLMs a versatile tool for modeling a wide range of data types.</p></li>
<li><p><strong>Generalized Mixed Models (GLMM):</strong> A more advanced approach that handles both fixed and random effects, useful for dealing with hierarchical or clustered data, and when the data structure involves more complex relationships.</p></li>
</ul>
<p>In this session, we will focus on two important types of regression: linear regression and logistic regression, and demonstrate how to perform them in R.</p>
</div>
<section id="simple-linear-regression-slr" class="level2" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="simple-linear-regression-slr"><span class="header-section-number">9.1</span> Simple Linear Regression (SLR)</h2>
<div style="text-align:justify">
<p>Simple Linear regression (SLR) is one of the most widely used statistical methods for modeling the relationship between a dependent variable and one independent variable. However, to ensure the model’s accuracy and validity, several assumptions must be met.</p>
</div>
<section id="assumptions-of-simple-linear-regression" class="level3" data-number="9.1.1">
<h3 data-number="9.1.1" class="anchored" data-anchor-id="assumptions-of-simple-linear-regression"><span class="header-section-number">9.1.1</span> Assumptions of Simple Linear Regression</h3>
<div style="text-align:justify">
<p>The acronym <strong>LINE</strong> helps us remember the key assumptions needed for making inferences and predictions with models based on linear least squares regression (LLSR).</p>
<p>In the case of simple linear regression with a single predictor <span class="math inline">\(X\)</span>, the assumptions are as follows:</p>
<ul>
<li><p><strong>L (Linear relationship)</strong>: The mean of the response variable <span class="math inline">\(Y\)</span> is linearly related to the predictor variable <span class="math inline">\(X\)</span>.</p></li>
<li><p><strong>I (Independence of errors)</strong>: The errors (or residuals) are independent, meaning that the distance between any two points from the regression line is unrelated.</p></li>
<li><p><strong>N (Normal distribution)</strong>: For each value of <span class="math inline">\(X\)</span>, the response <span class="math inline">\(Y\)</span> is normally distributed.</p></li>
<li><p><strong>E (Equal variance)</strong>: The variance (or standard deviation) of the responses is constant for all values of <span class="math inline">\(X\)</span>.</p></li>
</ul>
<p>These assumptions can be illustrated visually:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/linear_regression.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Assumptions for linear least squares regression (LLSR) <a href="https://bookdown.org/roback/bookdown-BeyondMLR/ch-MLRreview.html#assumptions-for-linear-least-squares-regression">(Roback and Legler, 2021)</a></figcaption><p></p>
</figure>
</div>
<ul>
<li><p>L: The expected value of <span class="math inline">\(Y\)</span> at each <span class="math inline">\(X\)</span> lies along the regression line.</p></li>
<li><p>I: We should verify that the design of the study ensures the errors are independent.</p></li>
<li><p>N: The values of <span class="math inline">\(Y\)</span> are normally distributed at each level of <span class="math inline">\(X\)</span>.</p></li>
<li><p>E: The spread of <span class="math inline">\(Y\)</span> is consistent across all levels of <span class="math inline">\(X\)</span>.</p></li>
</ul>
</div>
</section>
<section id="the-slr-model" class="level3" data-number="9.1.2">
<h3 data-number="9.1.2" class="anchored" data-anchor-id="the-slr-model"><span class="header-section-number">9.1.2</span> The SLR Model</h3>
<div style="text-align:justify">
<p>In SLR, the goal is to model the relationship between a dependent variable (response) and an independent variable (predictor). The model predicts the dependent variable based on the independent variable, helping us understand how changes in one variable impact the other.</p>
<p>The general form of a simple linear regression model is:</p>
<p><span class="math display">\[Y = \beta_0 + \beta_1 X + \epsilon\]</span></p>
<p>Where:</p>
<ul>
<li><p><span class="math inline">\(Y\)</span> is the dependent variable (the outcome we are predicting).</p></li>
<li><p><span class="math inline">\(X\)</span> is the independent variable (the predictor).</p></li>
<li><p><span class="math inline">\(\beta_0\)</span> is the intercept (the expected value of <span class="math inline">\(Y\)</span> when <span class="math inline">\(X=0\)</span>).</p></li>
<li><p><span class="math inline">\(\beta_1\)</span> is the slope (the change in <span class="math inline">\(Y\)</span> for each unit increase in <span class="math inline">\(X\)</span>).</p></li>
<li><p><span class="math inline">\(\epsilon\)</span> is the error term, representing the variability in <span class="math inline">\(Y\)</span> not explained by <span class="math inline">\(X\)</span>.</p></li>
</ul>
</div>
</section>
<section id="interpreting-the-model" class="level3" data-number="9.1.3">
<h3 data-number="9.1.3" class="anchored" data-anchor-id="interpreting-the-model"><span class="header-section-number">9.1.3</span> Interpreting the Model</h3>
<div style="text-align:justify">
<ul>
<li><p><strong>Intercept (<span class="math inline">\(\beta_0\)</span>)</strong>: The intercept tells us the expected value of the dependent variable when the independent variable is zero. However, in some cases, like the relationship between height and weight, interpreting the intercept might not make practical sense (e.g., predicting weight when height is zero).</p></li>
<li><p><strong>Slope (<span class="math inline">\(\beta_1\)</span>)</strong>: The slope indicates the change in the dependent variable for a one-unit change in the independent variable. For example, if we are looking at the relationship between height and weight, the slope tells us how much weight is expected to increase (or decrease) for every unit increase in height.</p></li>
<li><p><strong>Error term (<span class="math inline">\(\epsilon\)</span>)</strong>: The error term captures the variation in the dependent variable that is not explained by the independent variable. In practice, our model won’t perfectly predict every observation, and this error term accounts for the difference between observed values and the values predicted by the model.</p></li>
</ul>
</div>
</section>
</section>
<section id="simple-linear-regression-slr-using-r" class="level2" data-number="9.2">
<h2 data-number="9.2" class="anchored" data-anchor-id="simple-linear-regression-slr-using-r"><span class="header-section-number">9.2</span> Simple Linear Regression (SLR) Using R</h2>
<div style="text-align:justify">
<p>If the assumptions of simple linear regression are met, we can proceed with fitting the model to the data. In this section, we will explore how to perform simple linear regression using R. This method allows us to examine the relationship between a dependent variable (response) and an independent variable (predictor) and make predictions based on the data.</p>
</div>
<section id="simple-linear-regression-with-a-numeric-independent-variable" class="level3" data-number="9.2.1">
<h3 data-number="9.2.1" class="anchored" data-anchor-id="simple-linear-regression-with-a-numeric-independent-variable"><span class="header-section-number">9.2.1</span> Simple Linear Regression with a Numeric Independent Variable</h3>
<div style="text-align:justify">
<p>When dealing with a numeric independent variable, simple linear regression helps us understand how changes in the independent variable affect the dependent variable. In R, we can easily fit and evaluate this relationship using the lm() function.</p>
<p>Here’s an example of performing simple linear regression when the independent variable is numeric:</p>
<p><strong>Research Question</strong></p>
<p>Using the NHANES dataset, our research question is:</p>
<p>In adults, is there a relationship between height (independent variable) and weight (dependent variable)?</p>
</div>
<p><strong>Data Wrangling</strong></p>
<div style="text-align:justify">
<p>Before we perform the Simple Linear Regression, we need to load and clean the NHANES dataset.</p>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Instal and load packages</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages(pacman)</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(tidyverse, broom)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Load Data</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> NHANES<span class="sc">::</span>NHANES</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> df <span class="sc">|&gt;</span> </span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Age <span class="sc">&gt;=</span> <span class="dv">18</span>)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Set "White" as the reference category directly using factor()</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> df <span class="sc">|&gt;</span> </span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Race1 =</span> <span class="fu">factor</span>(Race1, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"White"</span>, <span class="st">"Black"</span>, <span class="st">"Mexican"</span>, <span class="st">"Hispanic"</span>, <span class="st">"Other"</span>)))</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Clean names</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> df <span class="sc">|&gt;</span> </span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>  janitor<span class="sc">::</span><span class="fu">clean_names</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>SLR Model</strong></p>
<div style="text-align:justify">
<p>Now, we build the linear regression model to examine the relationship between height and weight in adults.</p>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(weight <span class="sc">~</span> height, <span class="at">data =</span> df)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = weight ~ height, data = df)

Residuals:
    Min      1Q  Median      3Q     Max 
-41.329 -13.299  -2.887   9.673 149.022 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -78.06686    3.69698  -21.12   &lt;2e-16 ***
height        0.94804    0.02186   43.38   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 19.01 on 7412 degrees of freedom
  (67 observations deleted due to missingness)
Multiple R-squared:  0.2025,    Adjusted R-squared:  0.2024 
F-statistic:  1882 on 1 and 7412 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  term        estimate std.error statistic  p.value
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 (Intercept)  -78.1      3.70       -21.1 3.66e-96
2 height         0.948    0.0219      43.4 0       </code></pre>
</div>
</div>
<div style="text-align:justify">
<ul>
<li><p>The <code>lm()</code> function fits a simple linear regression model, and <code>summary()</code> provides detailed results including the regression coefficients, <span class="math inline">\(R^2\)</span>, and p-values.</p></li>
<li><p>The <code>tidy()</code> function from the <code>broom</code> package organizes the model output in a tidy format.</p></li>
</ul>
</div>
<p><strong>SLR Model Interpretation</strong></p>
<div style="text-align:justify">
<p>The Simple Linear Regression (SLR) model fits the relationship between height and weight in the adult population from the NHANES dataset. Below is a breakdown of the model output:</p>
<p><strong>Model Equation</strong></p>
<p>The model equation based on the output can be written as:</p>
<p><span class="math display">\[\hat{y} = -78.07 + 0.95 \times \text{Height}\]</span></p>
<p>Where:</p>
<ul>
<li><p><span class="math inline">\(\hat{y}\)</span> is the predicted weight (in kg)</p></li>
<li><p>The intercept (-78.07) represents the predicted weight when height is zero, which doesn’t have a practical interpretation in this context but is mathematically part of the model.</p></li>
<li><p>The slope (0.95) indicates that for each additional unit of height (in cm), the weight is expected to increase by approximately 0.95 kg, on average.</p></li>
</ul>
<p><strong>Coefficients</strong></p>
<ul>
<li><p>Intercept (-78.07): The negative intercept is not practically meaningful since height cannot be zero in adults, but it is part of the linear equation.</p></li>
<li><p>Height (0.95): The slope suggests that for every additional centimeter in height, weight increases by about 0.95 kg on average. The very small p-value (<span class="math inline">\(&lt;2e^-16\)</span>) indicates that the effect of height on weight is highly statistically significant.</p></li>
</ul>
<p><strong>Residuals</strong></p>
<p>The residuals show the differences between the observed and predicted values of weight:</p>
<ul>
<li><p>The minimum residual is -41.33, and the maximum is 149.02, indicating some large deviations.</p></li>
<li><p>The median residual is -2.89, suggesting that most predictions are close to the observed values.</p></li>
</ul>
<p><strong>Goodness of Fit</strong></p>
<p><strong>R-squared (0.2025)</strong> Approximately 20.25% of the variance in weight is explained by height, which suggests that while height has a significant impact on weight, other factors also influence weight substantially.</p>
<p><strong>Adjusted R-squared (0.2024)</strong> Very close to the R-squared, confirming the model is reliable for this data.</p>
<p><strong>Model Significance</strong></p>
<p>The F-statistic (1882) and its corresponding p-value (&lt;2.2e−16) indicate that the model is highly significant, meaning height is a useful predictor for weight in this dataset.</p>
<p>The interpretation shows that height has a positive and significant relationship with weight, but the relatively low <span class="math inline">\(R^2\)</span> value suggests that other factors besides height influence weight.</p>
</div>
</section>
<section id="simple-linear-regression-with-a-categorical-independent-variable" class="level3" data-number="9.2.2">
<h3 data-number="9.2.2" class="anchored" data-anchor-id="simple-linear-regression-with-a-categorical-independent-variable"><span class="header-section-number">9.2.2</span> Simple Linear Regression with a Categorical Independent Variable</h3>
<p>When dealing with a categorical independent variable, simple linear regression can be used to analyze how the different categories influence the dependent variable. In this case, we’ll explore the relationship between height and race in adults using the NHANES dataset.</p>
<p><strong>Research Question</strong></p>
<p>Is there an association between race and weight in adult individuals from the NHANES dataset?</p>
<p><strong>SLR Model</strong></p>
<p>In this analysis, we treat race as a categorical variable and examine its relationship with weight The regression equation for a categorical independent variable will include dummy coding (where one category is taken as the reference).</p>
<p>Here’s how you can perform the simple linear regression with a categorical variable in R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># SLR Model with Categorical Independent Variable</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>model_cat <span class="ot">&lt;-</span> <span class="fu">lm</span>(weight <span class="sc">~</span> race1, <span class="at">data =</span> df)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_cat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = weight ~ race1, data = df)

Residuals:
    Min      1Q  Median      3Q     Max 
-48.787 -15.028  -2.828  11.872 142.813 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    82.5284     0.2992 275.794  &lt; 2e-16 ***
race1Black      5.3582     0.7803   6.867 7.11e-12 ***
race1Mexican   -1.9117     0.8863  -2.157    0.031 *  
race1Hispanic  -4.2676     1.0616  -4.020 5.88e-05 ***
race1Other     -9.4982     0.9286 -10.229  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 21.02 on 7415 degrees of freedom
  (61 observations deleted due to missingness)
Multiple R-squared:  0.02501,   Adjusted R-squared:  0.02448 
F-statistic: 47.55 on 4 and 7415 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Tidying the output for better interpretation</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(model_cat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 5
  term          estimate std.error statistic  p.value
  &lt;chr&gt;            &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 (Intercept)      82.5      0.299    276.   0       
2 race1Black        5.36     0.780      6.87 7.11e-12
3 race1Mexican     -1.91     0.886     -2.16 3.10e- 2
4 race1Hispanic    -4.27     1.06      -4.02 5.88e- 5
5 race1Other       -9.50     0.929    -10.2  2.14e-24</code></pre>
</div>
</div>
<p><strong>SLR Model Interpretation</strong></p>
<p>:::{style=“text-align:justify”}</p>
<p>The Simple Linear Regression (SLR) model fits the relationship between race and weight in the adult population from the NHANES dataset. Below is a breakdown of the model output:</p>
<p><strong>Model Equation</strong></p>
<p>The model equation based on the output can be written as:</p>
<p><span class="math display">\[\hat{y} = 82.53 + 5.36 \times \text{(Black)} - 1.91 \times \text{(Mexican)} - 4.27 \times \text{(Hispanic)} - 9.50 \times \text{(Other)}\]</span></p>
<p><strong>Coefficients</strong></p>
<ul>
<li><p><strong>Intercept:</strong> The estimated average weight for individuals in the reference category (White) is 82.53 units.</p></li>
<li><p><code>race1Black</code>: Black individuals have an average weight that is 5.36 units heavier than the reference category (White).</p></li>
<li><p><code>race1Mexican</code>: Mexican individuals weigh, on average, 1.91 units less than the reference category (White).</p></li>
<li><p><code>race1Hispanic</code>: Hispanic individuals have an average weight that is 4.27 units less than the reference category (White).</p></li>
<li><p><code>race1Other</code>: Individuals in the Other category weigh, on average, 9.50 units less than the reference category (White).</p></li>
</ul>
<p><strong>Residuals</strong></p>
<p>Residuals indicate the differences between observed and predicted weights. They range from a minimum of -48.79 to a maximum of 142.81, showing variability in model predictions.</p>
<p><strong>Goodness of Fit</strong></p>
<ul>
<li><p><strong>Residual standard error:</strong> 21.02, indicating the average distance between observed and predicted values.</p></li>
<li><p><strong>Multiple R-squared:</strong> 0.02501, meaning that approximately 2.5% of the variability in weight is explained by race.</p></li>
<li><p><strong>Adjusted R-squared:</strong> 0.02448, which adjusts for the number of predictors in the model.</p></li>
</ul>
<p><strong>Model Significance</strong></p>
<p>The F-statistic is 47.55 with a p-value of &lt; 2.2e-16, indicating that the model is statistically significant and at least one of the race categories significantly predicts weight.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./inferential_statistics.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Inferential Statistics</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./hypothesis_testing.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">hypothesis_testing.html</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>